server:
  port: 8050
spring:
  threads:
    virtual:
      enabled: true
  profiles:
    active:
      - local
  mvc:
    apiversion:
      default: v1
      supported: v1
      use:
        header: X-API-VERSION
  http:
    clients:
      connect-timeout: 30s
      read-timeout: 30s
