spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_tracker_db
    driver-class-name: org.postgresql.Driver
    username: financial_tracker_apps
    password: financial_tracker_apps
    hikari:
      schema: financial_tracker_schema
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          financial-tracker-client:
            provider: identity
            client-id: financial-tracker-client
            authorization-grant-type: client_credentials
        provider:
          identity:
            token-uri: http://localhost:9000/oauth2/token

logging:
  level:
    org.zalando.logbook: INFO
    com.fabiankevin.app: INFO

management:
  tracing:
    enabled: false
  otlp:
    metrics:
      export:
        enabled: false