package com.fabiankevin.app.models.enums;

public enum EventAction {
    ADDED,
    UPDATED,
    DELETED,

    ITEM_ADDED,
    ITEM_UPDATED,
    ITEM_REMOVED,

    TRANSACTION_ADDED,
    TRANSACTION_UPDATED,
    TRANSACTION_DELETED,

    SHOPPING_LIST_COMPLETED,
    SHOPPING_LIST_CREATED,
    SHOPPING_LIST_UPDATED,
    SHOPPING_LIST_DELETED,

    INVITATION_RECEIVED,
    INVITATION_ACCEPTED,

    HOUSEHOLD_MEMBER_LEFT,
    HOUSEHOLD_MEMBER_JOINED
}
